// Simple fallback datasets for templates and blog posts
// Used when database connectivity fails so the frontend still receives content.

export const fallbackTemplates = [
  {
    id: 1,
    slug: 'agencia-digital',
    title: 'Agência Digital',
    content: '<p>Template focado em agências com foco em performance e branding.</p>',
    created_at: '2024-01-10',
    updated_at: '2024-01-10',
    meta: {
      heading: 'Landing page completa para agências',
      subheading: 'Estrutura pensada para captar leads e apresentar portfólio.',
      description:
        'Template otimizado para conversão, com blocos de depoimentos, serviços, portfólio e CTA para WhatsApp.',
      category: 'Agência',
      difficulty: 'Intermediário',
      price: 490,
      originalPrice: 790,
      pages: 6,
      features: ['SEO técnico otimizado', 'Formulários integrados', 'Seção de cases'],
      includes: ['Arquivos editáveis', 'Guia de publicação', 'Configuração inicial'],
      tags: ['agência', 'marketing', 'vendas'],
      demoUrl: 'https://demo.winove.com.br/agencia',
      images: {
        cover: '/assets/templates/agencia/cover.webp',
        gallery: ['/assets/templates/agencia/1.webp', '/assets/templates/agencia/2.webp'],
      },
      currency: 'BRL',
      contact: { whatsappIntl: '+55 47 99673-9013', defaultMessage: 'Quero conhecer o template Agência Digital' },
      ctaTexts: {
        buyTemplate: 'Comprar template',
        hosting: 'Quero com hospedagem',
        email: 'Preciso de e-mail profissional',
        bundle: 'Fazer pacote completo',
      },
      addons: {
        hosting: { name: 'Hospedagem otimizada', price: 149 },
        email: { name: 'E-mail corporativo', price: 69 },
      },
      bundles: [
        { name: 'Template + Publicação', price: 690 },
        { name: 'Template + SEO', price: 990 },
      ],
    },
  },
  {
    id: 2,
    slug: 'consultoria',
    title: 'Consultoria Empresarial',
    content: '<p>Estrutura para consultorias e escritórios apresentarem serviços.</p>',
    created_at: '2024-01-05',
    updated_at: '2024-01-05',
    meta: {
      heading: 'Site elegante para consultorias',
      subheading: 'Transmita autoridade e gere reuniões qualificadas.',
      description: 'Blocos de diferenciais, depoimentos, agenda integrada e CTA para contato.',
      category: 'Consultoria',
      difficulty: 'Iniciante',
      price: 420,
      pages: 5,
      features: ['Agenda integrada', 'Depoimentos em carrossel', 'Sessão de FAQ'],
      includes: ['Onboarding', 'Manual de edição'],
      tags: ['consultoria', 'b2b'],
      demoUrl: 'https://demo.winove.com.br/consultoria',
      images: {
        cover: '/assets/templates/consultoria/cover.webp',
        gallery: ['/assets/templates/consultoria/1.webp'],
      },
      currency: 'BRL',
      contact: { whatsappIntl: '+55 47 99673-9013', defaultMessage: 'Gostei do template de consultoria' },
      ctaTexts: {},
      addons: {},
      bundles: [],
    },
  },
  {
    id: 3,
    slug: 'ecommerce-minimal',
    title: 'E-commerce Minimal',
    content: '<p>Layout minimalista pensado para lojas de moda e acessórios.</p>',
    created_at: '2024-01-03',
    updated_at: '2024-01-03',
    meta: {
      heading: 'Loja virtual pronta para vender',
      subheading: 'Interface moderna com foco em velocidade e UX.',
      description: 'Inclui página de produto detalhada, lista de desejos e carrinho otimizado.',
      category: 'E-commerce',
      difficulty: 'Avançado',
      price: 790,
      pages: 8,
      features: ['Checkout otimizado', 'Lista de desejos', 'Avaliações de produto'],
      includes: ['Setup inicial', 'Manual de coleção'],
      tags: ['loja', 'ecommerce', 'moda'],
      demoUrl: 'https://demo.winove.com.br/ecommerce',
      images: {
        cover: '/assets/templates/ecommerce/cover.webp',
        gallery: ['/assets/templates/ecommerce/1.webp', '/assets/templates/ecommerce/2.webp'],
      },
      currency: 'BRL',
      contact: { whatsappIntl: '+55 47 99673-9013', defaultMessage: 'Quero o template E-commerce Minimal' },
      ctaTexts: {},
      addons: {},
      bundles: [],
    },
  },
];

export const fallbackBlogPosts = [
  {
    id: 101,
    slug: 'tendencias-marketing-2024',
    titulo: '5 Tendências de Marketing Digital para 2024',
    resumo: 'Descubra as principais apostas para performance e marca no próximo ano.',
    conteudo:
      '<p>Automação com IA, first-party data, UX focada em acessibilidade e outras tendências que vão ditar o ritmo em 2024.</p>',
    imagem_destacada: '/assets/blog/marketing-2024.webp',
    data_publicacao: '2024-01-12',
    autor: 'Equipe Winove',
    categoria: 'Marketing Digital',
  },
  {
    id: 102,
    slug: 'guia-templates-wix-studio',
    titulo: 'Como escolher o template Wix Studio ideal',
    resumo: 'Checklist prático para selecionar o tema certo para seu projeto.',
    conteudo:
      '<p>Veja como avaliar velocidade, SEO, blocos reutilizáveis e integrações antes de decidir pelo template.</p>',
    imagem_destacada: '/assets/blog/templates-wix.webp',
    data_publicacao: '2024-01-08',
    autor: 'Equipe Winove',
    categoria: 'Templates',
  },
  {
    id: 103,
    slug: 'cases-automatizacao-whatsapp',
    titulo: '3 cases de automação no WhatsApp que aumentaram conversões',
    resumo: 'Campanhas reais que usaram bots e fluxos para escalar atendimento.',
    conteudo:
      '<p>Como estruturamos jornadas de atendimento, qualificamos leads e reduzimos o tempo de resposta com automações.</p>',
    imagem_destacada: '/assets/blog/whatsapp-cases.webp',
    data_publicacao: '2024-01-03',
    autor: 'Equipe Winove',
    categoria: 'Automação',
  },
];
