CREATE TABLE IF NOT EXISTS propostas_comerciais (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT,
  template_id INT,
  status VARCHAR(50),
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefone VARCHAR(50),
  empresa VARCHAR(255) NOT NULL,
  cnpj VARCHAR(50),
  area_de_negocio VARCHAR(255),
  numero_de_funcionarios INT,
  setor VARCHAR(255),
  faturamento_anual DECIMAL(15,2),
  funcionarios_total INT,
  objetivos_projeto TEXT,
  escopo TEXT,
  servicos_incluidos TEXT,
  entregaveis TEXT,
  metodologia TEXT,
  cronograma TEXT,
  prazo_entrega VARCHAR(255),
  prazos_etapas TEXT,
  equipe_responsavel TEXT,
  experiencia_referencias TEXT,
  garantia TEXT,
  manutencao_suporte TEXT,
  treinamento TEXT,
  ferramenta_tecnologias TEXT,
  propriedade_intelectual TEXT,
  confiabilidade_seguranca TEXT,
  escopo_limite TEXT,
  fora_do_escopo TEXT,
  fluxos_aprovacao TEXT,
  canais_suporte TEXT,
  sla VARCHAR(255),
  forma_pagamento VARCHAR(255),
  valor_total DECIMAL(15,2),
  condicoes_pagamento TEXT,
  reajuste VARCHAR(255),
  impostos VARCHAR(255),
  datas_importantes TEXT,
  responsavel VARCHAR(255),
  revisao VARCHAR(255),
  assinatura_digital TEXT,
  aceite_termos TINYINT(1),
  data_envio DATETIME,
  data_resposta DATETIME,
  data_assinatura DATETIME,
  obs_internas TEXT,
  pdf_blob LONGBLOB,
  pdf_download_url VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
