CREATE TABLE IF NOT EXISTS `propostas_comerciais` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lead_id` INT NULL,
  `template_id` INT NULL,
  `status` VARCHAR(50) NOT NULL DEFAULT 'criada_via_site',
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(50) NULL,
  `empresa` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(32) NULL,
  `area_de_negocio` VARCHAR(255) NULL,
  `numero_de_funcionarios` VARCHAR(50) NULL,
  `setor` VARCHAR(255) NULL,
  `faturamento_anual` VARCHAR(255) NULL,
  `funcionarios_total` VARCHAR(50) NULL,
  `objetivos_projeto` TEXT NULL,
  `escopo` TEXT NULL,
  `servicos_incluidos` TEXT NULL,
  `entregaveis` TEXT NULL,
  `metodologia` TEXT NULL,
  `cronograma` TEXT NULL,
  `prazo_entrega` VARCHAR(255) NULL,
  `prazos_etapas` TEXT NULL,
  `equipe_responsavel` TEXT NULL,
  `experiencia_referencias` TEXT NULL,
  `garantia` TEXT NULL,
  `manutencao_suporte` TEXT NULL,
  `treinamento` TEXT NULL,
  `ferramenta_tecnologias` TEXT NULL,
  `propriedade_intelectual` TEXT NULL,
  `confiabilidade_seguranca` TEXT NULL,
  `escopo_limite` TEXT NULL,
  `fora_do_escopo` TEXT NULL,
  `fluxos_aprovacao` TEXT NULL,
  `canais_suporte` TEXT NULL,
  `sla` TEXT NULL,
  `forma_pagamento` VARCHAR(255) NULL,
  `valor_total` VARCHAR(255) NULL,
  `condicoes_pagamento` TEXT NULL,
  `reajuste` TEXT NULL,
  `impostos` TEXT NULL,
  `datas_importantes` TEXT NULL,
  `responsavel` VARCHAR(255) NULL,
  `revisao` VARCHAR(50) NULL,
  `assinatura_digital` TEXT NULL,
  `aceite_termos` TINYINT(1) NOT NULL DEFAULT 0,
  `data_envio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_resposta` DATETIME NULL,
  `data_assinatura` DATETIME NULL,
  `obs_internas` TEXT NULL,
  `pdf_blob` LONGBLOB NULL,
  `pdf_download_url` VARCHAR(500) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
